# The name uses to detect in witch hub you are
hub_id: 1
hud_name: Hub-%id%

# %player% -> Player display name || %message% -> Player send message
chat_format: "&f%player%&7: &f%message%"

# DON'T CHANGE
spawn_location: world;0.0;0.0;0.0;0.0;0.0
# DON'T CHANGE
